# Generated by Django 5.0.4 on 2024-04-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='title',
            field=models.CharField(default='Asdf', max_length=255),
            preserve_default=False,
        ),
    ]
